### ISSUE TITLE
Docker push ghcr workflow works twice

### ISSUE THREAD

**Issue by glazychev-art** [networkservicemesh/cmd-template#117]
### Description

These runs have the same tag - `f316920`
https://github.com/networkservicemesh/cmd-forwarder-vpp/actions/runs/5332639101/jobs/9662080619
https://github.com/networkservicemesh/cmd-forwarder-vpp/actions/runs/5332638380/jobs/9662079089

It looks like we don't need `workflow_run:` section
https://github.com/networkservicemesh/cmd-template/blob/main/.github/workflows/docker-push-ghcr.yml#L7-L11

**Comment by denis-tingaikin** [comment]
Seems like done
