### ISSUE TITLE
Add go generate ./... check for cmd-* applications

### ISSUE THREAD

**Issue by denis-tingaikin** [networkservicemesh/cmd-template#61]
We need to add `go generate ./...`  check on ci to verify that all applications have actual imports files.

**Comment by denis-tingaikin** [comment]
Example of PR where this problem happened https://github.com/networkservicemesh/cmd-nse-icmp-responder/pull/82#pullrequestreview-592956992

Potentially we have many repos where imports are outdated.

**Comment by Bolodya1997** [comment]
Working after #63 merged.
Example wrong PR: https://github.com/networkservicemesh/cmd-nsmgr/pull/200.
