### ISSUE TITLE
Make NSMBot commit message human-readable

### ISSUE THREAD

**Issue by denis-tingaikin** [networkservicemesh/cmd-template#64]
## Motivation

Look at https://github.com/networkservicemesh/deployments-k8s/pull/708#issue-608415883

As you can see commit message is not informative.

## Potential solution

Each commit from NSM bot should link only to the previous PR (that triggered the current commit).

**Comment by Mixaster995** [comment]
Tried some formatting changes for nsm bot message. Tested this on 4 repositories chain.
Result messages looks like this:
### Link - https://github.com/Mixaster995/test-actions-4/pull/22
### Image:

<img width="750" alt="Screenshot 2021-07-30 at 14 25 36" src="https://user-images.githubusercontent.com/26433765/127617017-cf1ab733-c5f2-44e1-b954-c6e242b4d833.png">

@edwarnicke what do you think about this changes?

**Comment by edwarnicke** [comment]
@Mixaster995 That looks amazing!

**Comment by Mixaster995** [comment]
Batch of PRs for changed message

api - https://github.com/networkservicemesh/api/pull/111

sdk - https://github.com/networkservicemesh/sdk/pull/1041
sdk-vpp - https://github.com/networkservicemesh/sdk-vpp/pull/328
sdk-k8s - https://github.com/networkservicemesh/sdk-k8s/pull/219
sdk-kernel - https://github.com/networkservicemesh/sdk-kernel/pull/303
sdk-sriov - https://github.com/networkservicemesh/sdk-sriov/pull/226

cmd-nsc-vpp - https://github.com/networkservicemesh/cmd-nsc-vpp/pull/210
cmd-nse-icmp-responder-vpp - https://github.com/networkservicemesh/cmd-nse-icmp-responder-vpp/pull/201
cmd-nse-firewall-vpp - https://github.com/networkservicemesh/cmd-nse-firewall-vpp/pull/29
cmd-forwarder-vpp - https://github.com/networkservicemesh/cmd-forwarder-vpp/pull/299

cmd-forwarder-sriov - https://github.com/networkservicemesh/cmd-forwarder-sriov/pull/250

**Comment by Bolodya1997** [comment]
https://github.com/networkservicemesh/integration-k8s-aws/pull/102
https://github.com/networkservicemesh/integration-k8s-packet/pull/106
https://github.com/networkservicemesh/integration-k8s-aks/pull/76

**Comment by denis-tingaikin** [comment]
All PRs merged. So closing this.
